apiVersion: v2
name: smapy
description: A SMA Inverter to InfluxDB submitter
type: application
version: 0.2.0
appVersion: v0.1.1
home: https://github.com/jonkerj/smapy
maintainers:
- name: jonkerj
  email: jorik@kippendief.biz
